#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode 4.2
#
# © Rei VILO, 2010-2012
# CC = BY NC SA
#


$(info  ---- info ----)
$(info Project)
$(info .    target      $(MAKECMDGOALS))
$(info .    name        $(PROJECT_NAME))

MAKEFILE_PATH = $(CURDIR)/Makefiles

include $(MAKEFILE_PATH)/Step1.mk